{
    'name': 'HR Employee Evaluation',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Performance Management System for Employee Evaluation',
    'description': 'Dynamic Performance Management System (PMS)',
    'author': 'Druksmart',
    'website': 'https://www.yourcompany.com',
    'depends': ['base', 'hr', 'mail', 'web', 'employee_pms'],
    'data': [
        'security/pms_security.xml',
        'security/ir.model.access.csv',
        'security/pms_record_rules.xml',
        'data/pms_data.xml',   
        'data/cron_jobs.xml',     
        'views/employee_planning_views.xml',
        'views/employee_appraisal_views.xml',
        'views/supervisor_plans_views.xml',
        'views/supervisor_appraisal_views.xml',
        'views/appraisal_template_views.xml',
        'views/competency_views.xml',
        'views/pms_cycle_views.xml',
        'views/scoring_engine_view.xml',
        'views/appraisal_competency_views.xml',
        'wizard/pms_enrollment_wizard_views.xml',
        'report/report_plan_summary.xml',
        'report/report_appraisal_summary.xml',
        'views/supervisor_cycle_views.xml',
        'views/appraisal_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'hr_employee_evaluation/static/src/kra_tabs/kra_tabs.*',
            'hr_employee_evaluation/static/src/competency/competency.*',
            'hr_employee_evaluation/static/src/chatter/chatter_toggle.js',
            'hr_employee_evaluation/static/src/chatter/chatter_toggle.css',
            'hr_employee_evaluation/static/src/scss/*.scss',
            'hr_employee_evaluation/static/img/expand_icon.svg'
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}